-- Migration: Create trivia system tables
-- Description: Add tables for trivia questions, sessions, and user responses

-- Trivia sessions to track quiz instances
CREATE TABLE trivia_sessions (
    id SERIAL PRIMARY KEY,
    session_name VARCHAR(255),
    difficulty_level VARCHAR(20) CHECK (difficulty_level IN ('easy', 'medium', 'hard', 'mixed')) DEFAULT 'mixed',
    question_count INTEGER DEFAULT 10,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP,
    score INTEGER DEFAULT 0,
    total_questions INTEGER DEFAULT 0,
    session_data JSONB -- Store additional session metadata
);

-- Trivia questions generated by AI
CREATE TABLE trivia_questions (
    id SERIAL PRIMARY KEY,
    session_id INTEGER REFERENCES trivia_sessions(id) ON DELETE CASCADE,
    question_text TEXT NOT NULL,
    question_type VARCHAR(20) CHECK (question_type IN ('multiple_choice', 'true_false', 'fill_blank', 'ranking')) NOT NULL,
    difficulty_level VARCHAR(20) CHECK (difficulty_level IN ('easy', 'medium', 'hard')) NOT NULL,
    category VARCHAR(50), -- e.g., 'top_tracks', 'discovery_dates', 'listening_patterns'
    correct_answer TEXT NOT NULL,
    options JSONB, -- For multiple choice questions
    explanation TEXT, -- Why this answer is correct
    data_source JSONB, -- Reference to the listening data used
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    order_in_session INTEGER -- Question order within the session
);

-- User responses to track performance
CREATE TABLE trivia_responses (
    id SERIAL PRIMARY KEY,
    session_id INTEGER REFERENCES trivia_sessions(id) ON DELETE CASCADE,
    question_id INTEGER REFERENCES trivia_questions(id) ON DELETE CASCADE,
    user_answer TEXT,
    is_correct BOOLEAN,
    response_time_seconds INTEGER, -- Time taken to answer
    answered_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Question generation history and performance tracking
CREATE TABLE trivia_generation_log (
    id SERIAL PRIMARY KEY,
    generation_type VARCHAR(50), -- 'session_generation', 'batch_generation'
    questions_requested INTEGER,
    questions_generated INTEGER,
    difficulty_level VARCHAR(20),
    categories_requested TEXT[], -- Array of requested categories
    openai_model VARCHAR(50),
    openai_usage JSONB, -- Token usage and cost tracking
    generation_time_seconds INTEGER,
    success BOOLEAN DEFAULT true,
    error_message TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    data_period_start DATE, -- What data period was analyzed
    data_period_end DATE
);

-- Create indexes for performance
CREATE INDEX idx_trivia_sessions_created_at ON trivia_sessions(created_at DESC);
CREATE INDEX idx_trivia_questions_session_id ON trivia_questions(session_id);
CREATE INDEX idx_trivia_questions_category ON trivia_questions(category);
CREATE INDEX idx_trivia_questions_difficulty ON trivia_questions(difficulty_level);
CREATE INDEX idx_trivia_responses_session_id ON trivia_responses(session_id);
CREATE INDEX idx_trivia_responses_question_id ON trivia_responses(question_id);
CREATE INDEX idx_trivia_generation_log_created_at ON trivia_generation_log(created_at DESC);

-- Add comments for documentation
COMMENT ON TABLE trivia_sessions IS 'Tracks individual trivia quiz sessions';
COMMENT ON TABLE trivia_questions IS 'AI-generated trivia questions based on listening data';
COMMENT ON TABLE trivia_responses IS 'User answers and performance tracking';
COMMENT ON TABLE trivia_generation_log IS 'Audit trail for question generation process';

COMMENT ON COLUMN trivia_questions.data_source IS 'JSONB containing the listening data that inspired this question';
COMMENT ON COLUMN trivia_questions.options IS 'JSONB array of answer options for multiple choice questions';
COMMENT ON COLUMN trivia_sessions.session_data IS 'Additional metadata like generation parameters, themes, etc.';
COMMENT ON COLUMN trivia_generation_log.openai_usage IS 'Token counts, model used, estimated cost';